Revert "hosting: fix service's name to match systemd unit"
This reverts commit 859b00eb7176bb0ecbdce546c90bec4327610c1c as puppet is not
able to manage the systed unit properly:

Error: /Stage[main]/Bind::Service/Service[bind9.service]: Could not evaluate: Could not find init script for 'bind9.service'